### ISSUE TITLE
BinTray is closing!

### ISSUE THREAD

**Issue by mrieser** [matsim-org/matsim-libs#1378]
We currently use Bintray to host our jar files. But Bintray is shutting down on May 1st 2021: https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/ . Additional info can be found in this article: https://www.infoq.com/news/2021/02/jfrog-jcenter-bintray-closure/ .

So we will have to decide where to host our jar-files (including the weekly snapshots) in the future and migrate everything.

(Update: oss.jfrog.org might not be affected, i.e. snapshots including the weekly releases might not be affected)

## Tasks
- [ ] decide on alternative Maven repository for hosting artifacts
- [ ] adapt deployment in pom.xml for:
    - [ ] matsim-libs
    - [ ] weekly snapshots
    - [ ] changes on Jenkins?
- [ ] migrate repository content to new repository
- [ ] change configured repository for dependencies in pom.xml for:
    - [ ] matsim-libs
    - [ ] matsim-example-project
    - [ ] others?
- [ ] Make sure that MATSim does not use any third-party dependencies hosted on Bintray, e.g. start a clean maven build with an empty local repository
    - [ ] Update affected third-party dependency repositories where possible
    - [ ] Keep a copy of required dependencies and self-host them if no other solution is possible.
- [ ] announce change in a MATSim news blog post.

## Alternatives
Potential alternatives for Maven repositories (feel free to add, I just wrote down what came to my mind)
- GitHub packages
- self-hosted
- simunto-hosted
- JFrog Platform
- Maven Central (only releases, no snapshots)
- OSSRH (Sonatype OSS Repository hosting, includes snapshots, allows publishing to Central)
- other?

We should try to figure out advantages and disadvantages for each alternative, especially regarding the hosting of the weekly-releases which quickly fill up any potential quota.

## Alternatives evaluation

|   | GitHub | Self-Hosted | Simunto-Hosted | JFrog | Maven Central | OSSRH |
|---|---|---|---|---|---|---|
| URL | https://github.com/features/packages | | | https://jfrog.com/pricing/#sass | | https://central.sonatype.org/pages/ossrh-guide.html |
| Storage-Quota,<br> Pricing | "free for public repositories", but no quota provided | . | . | 2 GB Storage / free <br> more storage / very expensive | | |
| Advantages | likely high-availability | . | . | likely high-availability | | |
| Disadvantages | . | own responsibility for availability | | | | |

**Comment by kainagel** [comment]
I thought that our weekly snapshots are on jfrog, and that jfrog remains.  ??

**Comment by mrieser** [comment]
> I thought that our weekly snapshots are on jfrog, and that jfrog remains. ??

Indeed, I added an update in the description above. But oss.jfrog.org is currently maintained with BinTray logins (https://www.jfrog.com/confluence/display/JFROG/Deploying+Snapshots+to+oss.jfrog.org), so we have to see what alternative way they provide to continue uploading to oss.jfrog

**Comment by sebhoerl** [comment]
https://packagecloud.io have an open source program, but not much information about it. We'd need to contact them specifically.

Just a note in case someone wants to play around with Github packages: It's best to do this in another repository, because once you add a single package it can never be deleted. So if we upload a 13-testing package and then decide not to go with Github, it will always show 13-testing as the latest package version to the users... just some previous experience ;-)

**Comment by michalmac** [comment]
We tried out packagecloud for some vsp projects a few years back, and it worked quite nice: https://packagecloud.io/matsim-vsp

I was also thinking about trying GitHub packages, simply because having everything in one place limits the overall maintenance burden. But there I have no experiences so far.

**Comment by michalmac** [comment]
Just wondering: maybe JFrog will offer some simplified migration to JFrog Artifactory? That would reduce the list of tasks on our side. Currently, I do not see anything like that.

**Comment by kainagel** [comment]
:-(

**Comment by michalmac** [comment]
I looked again into this issue. I have the following idea how to start on this issue. Maybe it's worth trying out?

I was thinking about replacing snapshots and weekly releases with releasing matsim after each PR is merged:
- use GitHub Actions to create a new release after each PR merge. It should probably take a few minutes (skipping tests as tests are run in the existing workflow; maybe we do not even need them on merging to master?)
- deploy to GitHub packages (everything in one place and, more importantly, there seems to be either no storage limit or a 50 GB limit)
- those releases would be versioned with a pull request ID appended to the matsim version, e.g. `13.0-PR1321` (which is similar to semantic versioning)
- (**later**) phase out releasing snapshots and switch to PR-labelled releases (that's the advantage over the weekly releases; staying on pure snapshots usually leads to lots of instabilities, failing builds etc. in other projects)
- (**later**) phase out releasing weekly releases (they are released not frequently enough to quickly include recent changes or hot fixes in matsim to dependant projects).

This idea is not meant to solve all issues in one go. It mainly focuses on points 1-2 (from the TODO list). The main goals: trying out GitHub (GitHub Actions + GitHub packages) and seeing if PR-labelled releases work okay with our other workflows (i.e. outside the matsim repo). If we are happy with this setup, we could then start working on the remaining TODOs.

**Comment by mrieser** [comment]
Thanks for picking this up again.

- Using PRs instead of Weekly is an interesting idea.
- Deploying to GitHub packages: +1

Regarding a potential quota: At Bintray, we had a 10GB quota, and quickly ran into it once we published weekly-releases (initially as non-snapshot versions). This was due to Maven also including the zip-files which contain all dependencies as release-artifacts. Thus, a release came close to 1 GB. I've modified this since, but there are still a few contribs which become quite big, so that in total a release is still around 100 or 200 MB if I remember correctly.
It might make sense to have another look at all the pom's if this could be further reduced. For example, I remember that contribs that used protobuf usually had like a 20MB javadoc-file, while all other contribs had very small javadoc-files. So there might be room for improvement.

**Comment by michalmac** [comment]
@mrieser Thanks for your feedback! I am about to start working on it (probably first in a separate repo) and will share the findings.

As for the size of releases, since they are only PR-based releases, I was thinking about making them as thin as possible (excluding javadocs and matsim-test). I hope this will significantly reduce the size of releases, but I cannot give any specific number yet.

**Comment by mrieser** [comment]
(from #1440)
> I was able to deploy to GitHub packages and then use the deployed jars in another local project. One caveat though: a public read token needs to be used (this is a current limitation of GitHub Packages). This is the currently suggested approach by GitHub according to https://github.community/t/partial-support-for-maven-snapshots/115628/12:

This required public read token troubles me a bit, as it prevents an easy copy/paste solution. As highlighted in the discussion linked to above, it looks as if (at the moment) GitHub Packages is rather thought as an internal deployment solution, and not an external repository for OpenSource projects. :-(

**Comment by mrieser** [comment]
Time is/was running short for the up-coming MATSim 13 release. 
GitHub Packages requires users to provide a token to access/download files from a repository, and is thus not very suitable for distributing releases to the public.
I have thus set up a maven repository on Simunto's repository server, and migrated most content of the old BinTray repo to the new one.

To use the new maven repository, use the following declaration in your pom.xml:

```xml
<repository>
    <!-- Repository for MATSim releases (MATSim is not on Maven central) -->
    <id>matsim</id>
    <url>https://repo.matsim.org/repository/matsim</url>
</repository>
```

**Comment by JustinPihony** [comment]
@mrieser Are you able to move https://bintray.com/matsim/matsim/matsim/0.11.0-2018w49 also?

**Comment by mrieser** [comment]
@JustinPihony I've added 0.11.0-2018w44, but only the core matsim library. If you also need some contrib, let me know which one. And I strongly suggest to switch to a newer version to benefit from the various improvements that took place in MATSim in the last 2.5 years.

**Comment by JustinPihony** [comment]
@mrieser Agreed. If you could migrate the decongestion contrib that would be very helpful. Otherwise we are all set - thanks!

**Comment by mrieser** [comment]
@JustinPihony decongestion is uploaded to the repository

**Comment by JustinPihony** [comment]
@mrieser Thanks - the pom has 
```
<parent>
<groupId>org.matsim</groupId>
<artifactId>contrib</artifactId>
<version>0.11.0-2018w44</version>
</parent>
```
So, we also need org/matsim/contrib/0.11.0-2018w44/contrib-0.11.0-2018w44.pom

**Comment by mrieser** [comment]
sorry I forgot the parent pom, should be up now.

**Comment by michalmac** [comment]
I just removed all 14.0-SNAPSHOT jars (already a bit outdated) from GitHub Packages just in case someone accidently uses them instead of the ones from our new matsim maven repo.
