### ISSUE TITLE
Add freight/logistics-related ConsistencyChecker(s)

### ISSUE THREAD

**Issue by kt86** [matsim-org/matsim-libs#3605]
This should include, e.g.,:
see sub-issues.

---
we think we should have two different checkers:

**Carriers**
   - [ ] one before Jsprit (all jobs theoretical solvable (timeWindows, size compared to vehicles etc.) --> see e.g. #3728 and #3729
  - [ ]  one after Jsprit (e.g. all jobs solved) -->  see e.g. #3729

*Checker for Carriers before Jsprit*
- [ ] unique Ids  ((Do we really need this? And what should be unique?)

**Logistics**

*before Run*
- [ ] unique Ids --> see #3606 

*after/while Run (Logistics)* --> see #3727 
- [ ] all jobs are still part of a plan 
- [ ] no job duplicates
